/*STEP:1-  AUDIT TABLE EXECUTE ON PRODUCTION DATABASE */
CREATE TABLE AUDIT
(PACAKGENAME VARCHAR(100) NULL,
STARTDATETIME DATETIME NULL,
ENDDATETIME DATETIME,
ACTUALTIMETAKEN AS (DATEDIFF(SECOND,STARTDATETIME,ENDDATETIME)),
ENTITY_KEY INT IDENTITY(1,1) NOT NULL,
)



/* STEP:2- EXECUTE ON PRODUCTION DATABASE */
CREATE PROCEDURE AUDIT_INSERT (@PACAKGENAME VARCHAR(100))
AS
INSERT INTO AUDIT(PACAKGENAME,STARTDATETIME)
SELECT @PACAKGENAME,GETDATE()


/* STEP:3 INSERT AUDIT ENTRY*/
EXEC AUDIT_INSERT 'Background_Education_SF'

/*STEP:4(UPDATE AUDIT ENTRY) UPDATE ENDDATETIME */
UPDATE AUDIT SET ENDDATETIME=GETDATE() WHERE PACAKGENAME='Background_Education_SF' AND
ENTITY_KEY=(SELECT MAX(ENTITY_KEY) FROM AUDIT WHERE PACAKGENAME='Background_Education_SF')

--STEP 1 & 2 RUN ON PRODUCT AND 3 & 4 USE IN EXECUTE PACKEGE TASK

--TO CHECK PACAKE RUN SUCCESSFULL OR NOT 
SELECT * FROM AUDIT

